# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

# all this does is package up the content from the pull request
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    on-failure: ABORT
    commands:
      # - echo $CODEBUILD_WEBHOOK_HEAD_REF > pr_trigger.txt
      # - cat pr_trigger.txt
      - npm run build
      - cdk deploy --require-approval never
artifacts:
  files:
    - '**/*'